CREATE TABLE KACRABT.ATTRIBUTUM_ERTEK
(
  ATTRIBUTUM_ID NUMBER(5)
, ERTEK VARCHAR2(20)
, CONSTRAINT ATTRIBUTUM_ERTEK_PK PRIMARY KEY
  (
  ATTRIBUTUM_ID
  , ERTEK
  )
  ENABLE
);

ALTER TABLE KACRABT.ATTRIBUTUM_ERTEK
ADD CONSTRAINT ATTRIBUTUM_ERTEK FOREIGN KEY
(
  ATTRIBUTUM_ID
)
REFERENCES KACRABT.ATTRIBUTUM
(
  ATTRIBUTUM_ID
)
ON DELETE CASCADE ENABLE;
