CREATE TABLE KACRABT.KATEGORIA
(
  KATEGORIA_ID NUMBER(5)
, KATEGORIA_NEV VARCHAR2(20)
, ATTRIBUTUM_ID NUMBER(5) NOT NULL
, CONSTRAINT KATEGORIA_PK PRIMARY KEY
  (
    KATEGORIA_ID
  )
  ENABLE
);
ALTER TABLE KACRABT.KATEGORIA
ADD CONSTRAINT ATTRIBUTUM_KAT_ID FOREIGN KEY
(
  ATTRIBUTUM_ID
)
REFERENCES KACRABT.ATTRIBUTUM
(
  ATTRIBUTUM_ID
)
ON DELETE CASCADE ENABLE;