CREATE TABLE KACRABT.ADMIN
(
  EMAIL VARCHAR2(50) 
  , JELSZO VARCHAR2(100)
  , ADMIN_NEV VARCHAR2(40)
  , SZUL_IDO DATE
  , NEM NUMBER check (NEM in('0','1'))
  , TELEFON NUMBER(11) NOT NULL
  , REG_DATUM TIMESTAMP
  , CONSTRAINT ADMIN_PK PRIMARY KEY
    (
      EMAIL
    )
    ENABLE
  );