CREATE TABLE KACRABT.LAKCIM
(
  EMAIL VARCHAR2(50) 
  , IR_SZAM NUMBER(4) NOT NULL
  , VAROS VARCHAR2(30)
  , UTCA VARCHAR2(20)
  , HAZSZAM NUMBER(3) NOT NULL
  , CONSTRAINT LAKCIM_PK PRIMARY KEY
    (
      EMAIL
    )
    ENABLE
  );
  ALTER TABLE KACRABT.LAKCIM
  ADD CONSTRAINT EMAIL FOREIGN KEY
  (
    EMAIL
  )
  REFERENCES KACRABT.FELHASZNALO
  (
    EMAIL
  )
  ON DELETE CASCADE ENABLE;