CREATE TABLE KACRABT.RENDELES_RESZLETEI
(
  RENDELES_ID NUMBER(5)
, TERMEK_ID NUMBER(5)
, ATTRIBUTUMOK VARCHAR2(500)
, DARAB_SZAM NUMBER(3) NOT NULL
, TERMEK_AR NUMBER(6) NOT NULL
, CONSTRAINT RENDELES_RESZLETEI_PK PRIMARY KEY
  (
    RENDELES_ID
  , TERMEK_ID
  )
  ENABLE
);



ALTER TABLE KACRABT.RENDELES_RESZLETEI
ADD CONSTRAINT TERMEK_ID FOREIGN KEY
(
  TERMEK_ID
)
REFERENCES KACRABT.TERMEK
(
  TERMEK_ID
)
ON DELETE CASCADE ENABLE;


ALTER TABLE KACRABT.RENDELES_RESZLETEI
ADD CONSTRAINT RENDELES_RESZ_ID FOREIGN KEY
(
  RENDELES_ID
)
REFERENCES KACRABT.RENDELES
(
  RENDELES_ID
)
ON DELETE CASCADE ENABLE;
