CREATE TABLE KACRABT.TERMEK
(
  TERMEK_ID NUMBER(5)
, KATEGORIA_ID NUMBER(5) NOT NULL
, TERMEK_NEV VARCHAR2(40)
, ROVID_LEIRAS VARCHAR(100)
, HOSSZU_LEIRAS VARCHAR(400)
, AR NUMBER(6) NOT NULL
, DARAB_SZAM NUMBER(3) NOT NULL
, CIMKE_ID NUMBER(5) NOT NULL
, CONSTRAINT TERMEK_ID_PK PRIMARY KEY
  (
  TERMEK_ID
  )
  ENABLE
);

ALTER TABLE KACRABT.TERMEK
ADD CONSTRAINT KATEGORIA_ID FOREIGN KEY
(
  KATEGORIA_ID
)
REFERENCES KACRABT.KATEGORIA
(
  KATEGORIA_ID
)
ON DELETE CASCADE ENABLE;

ALTER TABLE KACRABT.TERMEK
ADD CONSTRAINT CIMKE_ID FOREIGN KEY
(
  CIMKE_ID
)
REFERENCES KACRABT.CIMKE
(
  CIMKE_ID
)
ON DELETE CASCADE ENABLE;

