/*UPDATE CIMKE_ID*/
  
  CREATE OR REPLACE TRIGGER TR_CIMKE_ID
BEFORE UPDATE OF CIMKE_ID ON CIMKE
FOR EACH ROW
BEGIN
  UPDATE TERMEK
  SET CIMKE_ID = :NEW.CIMKE_ID
  WHERE CIMKE_ID = :OLD.CIMKE_ID;
  END;