/*UPDATE EMAIL - LAKCIM*/
 
CREATE OR REPLACE TRIGGER TR_EMAIL_LAKCIM
BEFORE UPDATE OF EMAIL ON FELHASZNALO
FOR EACH ROW
BEGIN
  UPDATE LAKCIM
  SET EMAIL = :NEW.EMAIL
  WHERE EMAIL = :OLD.EMAIL;
  END;