/*UPDATE KATEGORIA_ID */
 
 CREATE OR REPLACE TRIGGER TR_KATEGORIA_ID
BEFORE UPDATE OF KATEGORIA_ID ON KATEGORIA
FOR EACH ROW
BEGIN
  UPDATE TERMEK
  SET KATEGORIA_ID = :NEW.KATEGORIA_ID
  WHERE KATEGORIA_ID = :OLD.KATEGORIA_ID;
  END;